
-- CATEGORY
CREATE SEQUENCE CATEGORY_SEQ_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Và trigger để tự động tăng ID
CREATE OR REPLACE TRIGGER CATEGORY_TRG
BEFORE INSERT ON CATEGORY
FOR EACH ROW
BEGIN
SELECT CATEGORY_SEQ_ID.NEXTVAL
INTO :NEW.CATEGORY_ID
FROM DUAL;
END;
/

SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'CATEGORY_SEQ';
ALTER TABLE CATEGORY ADD VERSION NUMBER(10) DEFAULT 0;

-- CONFIG_VIEW
CREATE SEQUENCE CONFIG_VIEW_SEQ_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Và trigger để tự động tăng ID
CREATE OR REPLACE TRIGGER CONFIG_VIEW_TRG
    BEFORE INSERT ON CONFIG_VIEW
    FOR EACH ROW
BEGIN
    SELECT CONFIG_VIEW_SEQ_ID.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
END;
/

SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'CONFIG_VIEW_SEQ';
ALTER TABLE CONFIG_VIEW ADD VERSION NUMBER(10) DEFAULT 0;
-- DEPARTMENT